[package]
name = "yachiru"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comrak = "0.19.0"
frontmatter = "0.4.0"
fs_extra = "1.3.0"
pulldown-cmark = "0.8"
tera = "1.19.1"
